export const ENV = {
  OPENWEATHER_API_KEY: process.env.REACT_APP_OPENWEATHER_API_KEY,
  OPENWEATHER_BASE_URL_DAILY: process.env.REACT_APP_OPENWEATHER_BASE_URL_DAILY,
  OPEAWEATHER_BASE_URL_GEO: process.env.REACT_APP_OPEAWEATHER_BASE_URL_GEO,
  OPENWEATHER_BASE_URL_HOURLY:
    process.env.REACT_APP_OPENWEATHER_BASE_URL_HOURLY,
};
